package com.example.focusgate

enum class DouyinPageState {
    DOUYIN_UNKNOWN,
    DOUYIN_HOME_RECOMMEND,
    DOUYIN_SEARCH_PAGE,
    DOUYIN_SEARCH_RESULT,
    DOUYIN_VIDEO_FROM_SEARCH,
    DOUYIN_VIDEO_DETAIL,
    DOUYIN_USER_PROFILE,
    DOUYIN_COMMENT_OPEN,
    DOUYIN_SHOP_OR_LIVE,
    DOUYIN_WEBVIEW,
    DOUYIN_RETURNED_FROM_STUDY_LOOKUP,
    DOUYIN_RECHECK_PENDING,
    DOUYIN_PROMPT_SHOWING,
    DOUYIN_ENTERTAINMENT_ACTIVE,
    DOUYIN_COOLDOWN,
    DOUYIN_QUOTA_EXHAUSTED
}

object SearchGateDouyinLog {
    const val TAG = "SearchGateDouyinDebug"
}
