package com.example.focusgate

enum class PromptFlowState {
    IDLE,
    TODAY_QUOTA_UNSET,
    TODAY_QUOTA_CONFIRMED,
    PROMPT_SHOWING,
    SEARCH_REQUESTED,
    SEARCH_ACTIVITY,
    RETURNED_FROM_SEARCH,
    ENTERTAINMENT_ACTIVE,
    ENTERTAINMENT_ENDED_BY_USER,
    ENTERTAINMENT_ENDED_NATURALLY,
    ENTERTAINMENT_EXHAUSTED,
    PERMISSION_ERROR,
    SERVICE_RECOVERED,
    PROMPT_CLOSED_BY_ACTION
}
